### PR TITLE
complete to change Bunzz sdk to ether.js

### PR DESCRIPTION
**Pull request by smart-hede**
Completed to use ether.js instead of Bunzz SDK
https://bunzz-test.atlassian.net/browse/BUNZZ1-332

### CODE REVIEW

**Review by hitsuji-haneta — COMMENTED** [review]
@smart-ticky 
Great work! 👍 
Can I ask you to write README for showing how to use?
For example, users need to update `utils/constant.js`, right?

Please follow the style of erc20-minting-boilerplate, thank you!
https://github.com/lastrust/erc20-minting-boilerplate/blob/main/README.md

**Comment by smart-hede** [comment]
@hitsuji-haneta 
Updated README.md
Please check it and let me know.
Thank you.

**Review by hitsuji-haneta — COMMENTED** [review]
@smart-ticky 
Thank you so much!
Let me mention 3 more things🙏

(1) The NFT.Storage key is given as an env var, but others (chain info, RPC and so on) are configured by `constant.js`.
From the perspective of usability, all configurations must be done in the same manner if there is no reason like security.
Is there any reason to have 2 different configuration?

(2) Please show how to put "contract address" and "ABI" into the document🙂 It also should follow (1)

(3) You updated `<ROOT_DIR>/react` but please put it to the ROOT_DIR. We don't have to keep `vue/` and `js/` since they are using the SDK. The ERC20 boilerplate also has this structure🙂 
I mean,
■previous strucuture
```
/
|- js/
|- vue/
|- react/
    |- <THINGS YOU UPDATED>
``` 
■new
```
/
|-  <THINGS YOU UPDATED>
```

**Comment by smart-hede** [comment]
@hitsuji-haneta 
```
(1) The NFT.Storage key is given as an env var, but others (chain info, RPC and so on) are configured by constant.js.
From the perspective of usability, all configurations must be done in the same manner if there is no reason like security.
Is there any reason to have 2 different configuration?
```
DApp is decentralized application.
In other words, we need to share the contract address with users on github.
After dapp creator create the dapp using our boilerplate, they will share the app source code creating a new repo in their organization.
Then the dapp users should be able to see the contract address on github.
If you check other dapps, you can find they shared the contract addresses on github repo.

However, the infrakey and storage key are private.
So need to add these in .env file.

**Comment by smart-hede** [comment]
For others, I'll modify the structure and readme

**Comment by hitsuji-haneta** [comment]
@smart-ticky 
> In other words, we need to share the contract address with users on github.

I see. you're right🙂
Then, could you add this idea to the README?
Users might be confused if there is no explanation.

**Comment by smart-hede** [comment]
@hitsuji-haneta 
updated the structure and readme

**Review by hitsuji-haneta — APPROVED** [review]
@smart-ticky 
LGTM, thank you so much!

**Pull request merged**
